// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxsOJEvN2IQntZTG5Wz2XbUSMJqJ9Gb0',
    appId: '1:404200478715:web:b09e9942a6ded4cfd5dd5e',
    messagingSenderId: '404200478715',
    projectId: 'bingo-f95a7',
    authDomain: 'bingo-f95a7.firebaseapp.com',
    storageBucket: 'bingo-f95a7.firebasestorage.app',
    measurementId: 'G-C5G393WWGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMtPzvpV5kicyUyx39Hd6na5JxVkhcfs',
    appId: '1:404200478715:android:ea53461afccc726ed5dd5e',
    messagingSenderId: '404200478715',
    projectId: 'bingo-f95a7',
    storageBucket: 'bingo-f95a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeuNPghLT8-yafhdYJd06qHgZmG_6h_c',
    appId: '1:404200478715:ios:d9fe6135e58a3315d5dd5e',
    messagingSenderId: '404200478715',
    projectId: 'bingo-f95a7',
    storageBucket: 'bingo-f95a7.firebasestorage.app',
    iosBundleId: 'com.example.bingoFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeuNPghLT8-yafhdYJd06qHgZmG_6h_c',
    appId: '1:404200478715:ios:d9fe6135e58a3315d5dd5e',
    messagingSenderId: '404200478715',
    projectId: 'bingo-f95a7',
    storageBucket: 'bingo-f95a7.firebasestorage.app',
    iosBundleId: 'com.example.bingoFirebaseExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxsOJEvN2IQntZTG5Wz2XbUSMJqJ9Gb0',
    appId: '1:404200478715:web:88135fefccf4feced5dd5e',
    messagingSenderId: '404200478715',
    projectId: 'bingo-f95a7',
    authDomain: 'bingo-f95a7.firebaseapp.com',
    storageBucket: 'bingo-f95a7.firebasestorage.app',
    measurementId: 'G-XPT7L6GZ0X',
  );
}
